# Site settings
title: Unnamed Project
#description: 
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: The Unnamed Project
#user_description: I'm a Software Engineer from Argentina, always searching for the next challenge; no task is too scary nor too difficult. Lately I have been immersed in world of Giving Circles working with Grapevine, a California based startup trying to improve the world through collaborative giving. I'm the first engineer they hired to work on the platform.
user_title: Hello ðŸ‘‹, I am Natalia Soares
email: natalia.nrsoares@gmail.com
github_username: natalianrs
linkedin_username: natalianrs
# twitter_username: lorem_ipsum
#instagram_username: lorem_ipsum
#facebook_username: lorem_ipsum
# medium_username: lorem_ipsum
#medium_url: lorem_ipsum
# gplus_username:  lorem_ipsum

exclude: ['package.json', 'src' , 'node_modules']
